"""init schema

Revision ID: eca054a3dbbd
Revises: 
Create Date: 2026-03-30 14:51:33.559718
"""
from __future__ import annotations

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'eca054a3dbbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier_performance_metrics',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=False),
    sa.Column('service_lane', sa.String(length=256), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('median_delay_days', sa.Float(), nullable=True),
    sa.Column('on_time_rate', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier', 'service_lane', 'year_month')
    )
    op.create_table('demurrage_tariffs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('terminal_locode', sa.String(length=10), nullable=False),
    sa.Column('vehicle_type', sa.String(length=64), nullable=False),
    sa.Column('free_days', sa.Integer(), nullable=False),
    sa.Column('daily_rate_usd', sa.Float(), nullable=True),
    sa.Column('daily_rate_ngn', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('terminal_locode', 'vehicle_type', 'effective_from')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('currency_pair', sa.String(length=32), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fx_rates_pair_observed_at', 'fx_rates', ['currency_pair', 'observed_at'], unique=False)
    op.create_table('port_congestion_readings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('port_locode', sa.String(length=10), nullable=False),
    sa.Column('delay_days', sa.Float(), nullable=False),
    sa.Column('queue_vessels', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_port_congestion_readings_port_observed', 'port_congestion_readings', ['port_locode', 'observed_at'], unique=False)
    op.create_table('port_congestion_seasonality',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('port_locode', sa.String(length=10), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('median_wait_days', sa.Float(), nullable=False),
    sa.Column('p75_wait_days', sa.Float(), nullable=True),
    sa.Column('p90_wait_days', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port_locode', 'month')
    )
    op.create_table('raw_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_health',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('source_class', sa.String(length=64), nullable=False),
    sa.Column('automation_safety', sa.String(length=32), nullable=False),
    sa.Column('business_safe_default', sa.Boolean(), nullable=False),
    sa.Column('source_status', sa.String(length=32), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stale_after_seconds', sa.Integer(), nullable=False),
    sa.Column('degraded_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    op.create_table('tracking_cases',
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('tracked_service_code', sa.String(length=64), nullable=True),
    sa.Column('tracked_voyage_reference', sa.String(length=128), nullable=True),
    sa.Column('tracked_imo', sa.String(length=20), nullable=True),
    sa.Column('tracked_mmsi', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('vessels',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('imo', sa.String(length=20), nullable=True),
    sa.Column('mmsi', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('flag', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imo'),
    sa.UniqueConstraint('mmsi')
    )
    op.create_table('carrier_schedules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=False),
    sa.Column('voyage_code', sa.String(length=128), nullable=True),
    sa.Column('vessel_name', sa.String(length=256), nullable=True),
    sa.Column('vessel_imo', sa.String(length=20), nullable=True),
    sa.Column('port_locode', sa.String(length=10), nullable=False),
    sa.Column('etd', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_event_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_carrier_schedules_carrier_scraped_at', 'carrier_schedules', ['carrier', 'scraped_at'], unique=False)
    op.create_index('ix_carrier_schedules_vessel_imo_eta', 'carrier_schedules', ['vessel_imo', 'eta'], unique=False)
    op.create_table('latest_positions',
    sa.Column('mmsi', sa.String(length=20), nullable=False),
    sa.Column('imo', sa.String(length=20), nullable=True),
    sa.Column('vessel_name', sa.String(length=256), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('sog_knots', sa.Float(), nullable=True),
    sa.Column('cog_degrees', sa.Float(), nullable=True),
    sa.Column('heading_degrees', sa.Float(), nullable=True),
    sa.Column('navigation_status', sa.String(length=64), nullable=True),
    sa.Column('destination_text', sa.String(length=256), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_event_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('mmsi')
    )
    op.create_table('port_observations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('port_locode', sa.String(length=10), nullable=False),
    sa.Column('terminal_name', sa.String(length=256), nullable=True),
    sa.Column('vessel_name', sa.String(length=256), nullable=True),
    sa.Column('vessel_imo', sa.String(length=20), nullable=True),
    sa.Column('vessel_mmsi', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_event_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_port_observations_port_observed_at', 'port_observations', ['port_locode', 'observed_at'], unique=False)
    op.create_index('ix_port_observations_vessel_imo_observed_at', 'port_observations', ['vessel_imo', 'observed_at'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('vessel_id', sa.String(length=64), nullable=True),
    sa.Column('mmsi', sa.String(length=20), nullable=False),
    sa.Column('imo', sa.String(length=20), nullable=True),
    sa.Column('vessel_name', sa.String(length=256), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('sog_knots', sa.Float(), nullable=True),
    sa.Column('cog_degrees', sa.Float(), nullable=True),
    sa.Column('heading_degrees', sa.Float(), nullable=True),
    sa.Column('navigation_status', sa.String(length=64), nullable=True),
    sa.Column('destination_text', sa.String(length=256), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_event_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quarantined_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('raw_event_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload_text', sa.Text(), nullable=True),
    sa.Column('quarantined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('booking_ref', sa.String(length=128), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=False),
    sa.Column('service_lane', sa.String(length=256), nullable=True),
    sa.Column('load_port', sa.String(length=8), nullable=True),
    sa.Column('discharge_port', sa.String(length=8), nullable=True),
    sa.Column('cargo_type', sa.String(length=128), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('declared_departure_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declared_eta_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_event_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_ref')
    )
    op.create_table('voyage_signals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vessel_imo', sa.String(length=20), nullable=True),
    sa.Column('vessel_mmsi', sa.String(length=20), nullable=True),
    sa.Column('service_code', sa.String(length=64), nullable=True),
    sa.Column('destination_text', sa.String(length=256), nullable=True),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_event_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clearance_checklists',
    sa.Column('shipment_id', sa.String(length=64), nullable=False),
    sa.Column('form_m_approved', sa.Boolean(), nullable=False),
    sa.Column('bl_received', sa.Boolean(), nullable=False),
    sa.Column('paar_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paar_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customs_duty_paid', sa.Boolean(), nullable=False),
    sa.Column('trucking_booked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=256), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('shipment_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_chunks_source_type_ingested', 'document_chunks', ['source_type', 'ingested_at'], unique=False)
    op.create_table('eta_revision_log',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('shipment_id', sa.String(length=64), nullable=True),
    sa.Column('carrier', sa.String(length=64), nullable=True),
    sa.Column('revision_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delta_hours', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eta_revision_log_shipment_revision_at', 'eta_revision_log', ['shipment_id', 'revision_at'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('shipment_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_vessels',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('shipment_id', sa.String(length=64), nullable=False),
    sa.Column('vessel_id', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'vessel_id')
    )
    op.create_table('standby_agents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('user_email', sa.String(length=320), nullable=True),
    sa.Column('shipment_id', sa.String(length=64), nullable=True),
    sa.Column('condition_text', sa.Text(), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rule_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fire_count', sa.Integer(), nullable=False),
    sa.Column('last_result', sa.Text(), nullable=True),
    sa.Column('last_match_state', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_standby_agents_status_next_run', 'standby_agents', ['status', 'next_run_at'], unique=False)
    op.create_index('ix_standby_agents_user_created', 'standby_agents', ['user_id', 'created_at'], unique=False)
    op.create_table('voyage_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('shipment_id', sa.String(length=64), nullable=True),
    sa.Column('vessel_imo', sa.String(length=20), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standby_agent_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('action_executed', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['standby_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_standby_agent_runs_agent_started', 'standby_agent_runs', ['agent_id', 'started_at'], unique=False)
    op.create_table('standby_digest_queue',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('user_email', sa.String(length=320), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('shipment_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('digest_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['standby_agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_standby_digest_queue_status_due', 'standby_digest_queue', ['status', 'digest_due_at'], unique=False)
    op.create_index('ix_standby_digest_queue_user_due', 'standby_digest_queue', ['user_id', 'digest_due_at'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('unread', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['standby_agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_notifications_user_created', 'user_notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_user_notifications_user_unread', 'user_notifications', ['user_id', 'unread'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_notifications_user_unread', table_name='user_notifications')
    op.drop_index('ix_user_notifications_user_created', table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index('ix_standby_digest_queue_user_due', table_name='standby_digest_queue')
    op.drop_index('ix_standby_digest_queue_status_due', table_name='standby_digest_queue')
    op.drop_table('standby_digest_queue')
    op.drop_index('ix_standby_agent_runs_agent_started', table_name='standby_agent_runs')
    op.drop_table('standby_agent_runs')
    op.drop_table('voyage_events')
    op.drop_index('ix_standby_agents_user_created', table_name='standby_agents')
    op.drop_index('ix_standby_agents_status_next_run', table_name='standby_agents')
    op.drop_table('standby_agents')
    op.drop_table('shipment_vessels')
    op.drop_table('evidence')
    op.drop_index('ix_eta_revision_log_shipment_revision_at', table_name='eta_revision_log')
    op.drop_table('eta_revision_log')
    op.drop_index('ix_document_chunks_source_type_ingested', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('clearance_checklists')
    op.drop_table('voyage_signals')
    op.drop_table('shipments')
    op.drop_table('quarantined_events')
    op.drop_index('idx_positions_geom', table_name='positions', postgresql_using='gist')
    op.drop_table('positions')
    op.drop_index('ix_port_observations_vessel_imo_observed_at', table_name='port_observations')
    op.drop_index('ix_port_observations_port_observed_at', table_name='port_observations')
    op.drop_table('port_observations')
    op.drop_index('idx_latest_positions_geom', table_name='latest_positions', postgresql_using='gist')
    op.drop_table('latest_positions')
    op.drop_index('ix_carrier_schedules_vessel_imo_eta', table_name='carrier_schedules')
    op.drop_index('ix_carrier_schedules_carrier_scraped_at', table_name='carrier_schedules')
    op.drop_table('carrier_schedules')
    op.drop_table('vessels')
    op.drop_table('tracking_cases')
    op.drop_table('source_health')
    op.drop_table('raw_events')
    op.drop_table('port_congestion_seasonality')
    op.drop_index('ix_port_congestion_readings_port_observed', table_name='port_congestion_readings')
    op.drop_table('port_congestion_readings')
    op.drop_index('ix_fx_rates_pair_observed_at', table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_table('demurrage_tariffs')
    op.drop_table('carrier_performance_metrics')
    # ### end Alembic commands ###
